name: build-pkgs
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
jobs:
  build:
    strategy:
      matrix:
        repos: [ ascii-image-converter-git,nginx-rtmp,linux-xanmod,qrcp,hexo-cli,mongodb-bin,lyrebird,obsidian-2-theme-git,obsidian-icon-theme-git,freechat-git,gdm-tools-git,telegram-desktop-userfonts ]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: weiliang1503/build-aur-action@master
        with:
          repo-name: ${{ matrix.repos }}
      - uses: ncipollo/release-action@v1.8.10
        with:
          allowUpdates: True
          tag: "x86_64"
          artifacts: "./*/*.zst"
          token: ${{ secrets.GITHUB_TOKEN }}
