name: 自動に PKG の DB を更新する
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * ?'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: weiliang1503/update-db-for-repo@master
      with:
        repo-name: zhaose-repo 
    - uses: ncipollo/release-action@v1.8.10
      with:
        allowUpdates: true
        tag: "x86_64"
        artifacts: "./zhaose-repo.*"
        token: ${{ secrets.GITHUB_TOKEN }}
